# Generated by Django 4.2.2 on 2023-08-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineaDeOro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id_autobus', models.IntegerField(primary_key=True, serialize=False)),
                ('placa_autobus', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_chofer', models.CharField(max_length=50)),
                ('ape_pat_chofer', models.CharField(max_length=50)),
                ('ape_mat_chofer', models.CharField(max_length=50)),
                ('telefono_chofer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id_origen', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad_origen', models.CharField(max_length=50)),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_viaje', models.DateField()),
                ('id_autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineaDeOro.autobus')),
                ('id_chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineaDeOro.chofer')),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineaDeOro.destino')),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineaDeOro.origen')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id_asiento', models.IntegerField(primary_key=True, serialize=False)),
                ('asiento_ocupado', models.BooleanField(default=False)),
                ('id_autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineaDeOro.autobus')),
            ],
        ),
    ]
